// Code generated by MockGen. DO NOT EDIT.
// Source: ./dao/txn_dao.go

// Package dao is a generated GoMock package.
package dao

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTxnDao is a mock of TxnDao interface
type MockTxnDao struct {
	ctrl     *gomock.Controller
	recorder *MockTxnDaoMockRecorder
}

// MockTxnDaoMockRecorder is the mock recorder for MockTxnDao
type MockTxnDaoMockRecorder struct {
	mock *MockTxnDao
}

// NewMockTxnDao creates a new mock instance
func NewMockTxnDao(ctrl *gomock.Controller) *MockTxnDao {
	mock := &MockTxnDao{ctrl: ctrl}
	mock.recorder = &MockTxnDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTxnDao) EXPECT() *MockTxnDaoMockRecorder {
	return m.recorder
}

// CreateTxnEntry mocks base method
func (m *MockTxnDao) CreateTxnEntry(userName, merchantName string, txnAmt int) error {
	ret := m.ctrl.Call(m, "CreateTxnEntry", userName, merchantName, txnAmt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTxnEntry indicates an expected call of CreateTxnEntry
func (mr *MockTxnDaoMockRecorder) CreateTxnEntry(userName, merchantName, txnAmt interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTxnEntry", reflect.TypeOf((*MockTxnDao)(nil).CreateTxnEntry), userName, merchantName, txnAmt)
}
